### ISSUE TITLE
(1d4)#(d20+3)的问题

### ISSUE THREAD

**Issue by KeithTsao** [sealdice/dicescript#2]
场景为某生物进行了`1d4`次相同的攻击，每次攻击检定为`d20+3`，在现有的语法/海豹骰里似乎只能用两条语句来解决；
从手册上看`#`表示骰点次数并非dicescript语法，而是骰子的一项扩展功能（而且`1d4#d20`会被解析成`4#1dd20`）；

那么之后有没有可能加入`#`作为运算符或者在骰子里解析类似标题这样的语句呢？

**Comment by fy0** [comment]
不准备加为运算符，因为习惯语法 # 能出现在句中任意的地方，这很奇怪
这个式子在fvtt里有无等价的一键骰法？可以考虑支持对应的语法

**Comment by KeithTsao** [comment]
翻了一遍fvtt的语法，似乎可以用/r {1d4, d20+3, d20+3, d20+3, d20+3}然后手动数出来，不过我还没在fvtt上试过

**Comment by fy0** [comment]
ds里用[]表示了数组：
[1d4, d20+3, d20+3, d20+3, d20+3]

过程: [3[1d4=3=3], 12[d20=12=12]+3, 2[d20=2=2]+3, 12[d20=12=12]+3, 18[d20=18=18]+3]
结果: [3, 15, 5, 15, 21]
栈顶: 1 层数:0 算力: 37

**Comment by KeithTsao** [comment]
感谢，总之有一种可以用的办法了
